language: node_js
node_js:
- lts/*
sudo: required
cache:
  directories:
  - node_modules
yarn:
  Installed: 1.19.1
  Candidate: 1.19.1
before_script: chmod 777 *.sh
script:
- "./deploy.sh"

before_install:
- chmod 777 /root
- openssl aes-256-cbc -K $encrypted_b44f898cc0ec_key -iv $encrypted_b44f898cc0ec_iv
  -in id_rsa.enc -out /root/.ssh/id_rsa -d
branch: master
notifications:
  email: true

# 添加 SSH 信任列表
addons:
  ssh_known_hosts: 182.92.60.170
# 执行部署脚本（）
after_success:
  - rm -rf root@182.92.60.170:/home/Jaqea/Blog/*
  - scp -o stricthostkeychecking=no -r ./dist/* root@182.92.60.170:/home/Jaqea/Blog
