language: node_js
node_js:
- lts/*
sudo: required
cache:
  directories:
  - node_modules
yarn:
  Installed: 1.19.1
  Candidate: 1.19.1
before_script: chmod 777 *.sh
script:
- "./deploy.sh"
branch: master
notifications:
  email: true
addons:
  ssh_known_hosts: 182.92.60.170
after_success:
- rm -rf root@182.92.60.170:/home/Jaqea/Blog/*
- scp -o stricthostkeychecking=no -r ./dist/* root@182.92.60.170:/home/Jaqea/Blog
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
