language: node_js
node_js:
  - "lts/*"
sudo: required
cache:
  directories:
    - node_modules
yarn:
  Installed: 1.19.1
  Candidate: 1.19.1
# branches:
#   only:
#   - master
before_script: chmod 777 *.sh
script: # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - ./deploy.sh
branch: master

notifications: # 设置通知项
  email: true