language: node_js
node_js:
  - "lts/*"
sudo: required
cache:
  directories:
    - node_modules
yarn:
  Installed: 1.19.1
  Candidate: 1.19.1
# branches:
#   only:
#   - master


script: # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - yarn build
deploy: 
  local_dir: docs/.vuepress/dist
  github-token: $GIT_REPO_TOKEN
  target-branch: gh-pages
  keep-history: true
  on:   
    branch: master

notifications: # 设置通知项
  email: true